server:
  port: 8080  # Application runs on port 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/smart_task_db
    username: root
    password: root
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/smart_task_db
    user: root
    password: root
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:jeevaraniarumugam99@gmail.com}
    password: "${MAIL_PASSWORD:ksfi qnxz htnz dumv}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: my-super-secret-key-my-super-secret-key
  expiration: 3600000

app:
  frontend-base-url: http://localhost:5173
  mail:
    enabled: true
    from: ${MAIL_FROM:jeevaraniarumugam99@gmail.com}

logging:
  config: classpath:logback-spring.xml
